#' trunc_ibs
#'
#' Truncates the min/max of the IBS matrix to graphmin/graphmax
#' to make plots easier to read
#'
#' @keywords internal
#'
#' @param ibs.mat Matrix of pairwise IBS sharing at the site of interest. Likely generated by ibs.matrix()
#' @param graphmin Vector of risk haplotype identifiers (one per case subject).
#' @param graphmax Genomic position at start of site of interest.
#' @return Matrix of truncated pairwise IBS sharing between case individuals across site of interest.
#' @export
trunc_ibs_mat <- function(ibs.mat, graphmin = NULL, graphmax = NULL) {
  trunc.out <- ibs.mat
  if (!is.null(graphmin)) {
    trunc.out[which(trunc.out != 0 & trunc.out < graphmin)] <- graphmin
  }
  if (!is.null(graphmax)) {
    trunc.out[trunc.out > graphmax] <- graphmax
  }
  return(trunc.out)
}